### ISSUE TITLE
--no-plugins option not working

### ISSUE THREAD

**Issue by subhojit777** [axelerant/db-docker#3]
### Steps to replicate:

1. Setup a Drupal 8 project using Lando 3.0.5
1. Install `db-docker` as per the installation steps https://github.com/axelerant/db-docker#installation
1. Execute `lando composer db-docker --no-plugins`
1. I got error `Command "db-docker" is not defined`.

I am using Docker Desktop version 2.3.0.3 (45519) on Mac

**Comment by subhojit777** [comment]
FYI @hussainweb

**Comment by subhojit777** [comment]
Even after adding the tooling I got the error.

```yml
name: standup-bot-rest
recipe: drupal8
config:
  webroot: web
  xdebug: true
  config:
    php: .lando.php.ini
services:
  appserver:
    type: php
    build_as_root:
      - pecl install ds
      - docker-php-ext-enable ds
tooling:
  db-docker:
    service: appserver
    description: Runs composer db-docker command
    cmd: composer db-docker
```
